const fs = require('fs');
const path = require('path');

// 您提供的最新cookie数据
const newSessdata = '4282cb5c%2C1783283626%2C3f494%2A12CjAsqfXC9Or3IjeZY1e07RgiRh8zzrFdyhCDCDjv_0NrId9jxzc3gjf5yGXv-37oj2wSVkV3SXBRLTQyckF5dElWRk9oSlNuRGR4V3JERWVCNmRCeWgxWFYzV2cwVU1VMUdOOHZhcXFnYzRGWElvZFRvdjBsc0dESlVMSDVLS3Q5TzhrcHdOLUlnIIEC';
const newBiliJct = '141eeb64e472d403d2a8031b87613894';

const cookiePath = '/mnt/c/Users/user/Desktop/jiaobenbili/cookie.txt';

function updateCookies() {
    try {
        console.log('🔄 开始更新B站cookie...');
        
        // 备份原有cookie文件
        if (fs.existsSync(cookiePath)) {
            const backupPath = `${cookiePath}.backup.${Date.now()}`;
            fs.copyFileSync(cookiePath, backupPath);
            console.log(`📋 原cookie文件已备份到: ${backupPath}`);
        }

        // 当前时间戳 (过期时间设置为很久以后)
        const expireTime = Math.floor(Date.now() / 1000) + (365 * 24 * 60 * 60); // 1年后过期

        // 生成新的cookie文件内容 (Netscape格式)
        const cookieLines = [
            '# Netscape HTTP Cookie File',
            '# Generated by Cookie Update Script',
            `# ${new Date().toISOString()}`,
            '',
            // 基本域名cookie
            `.bilibili.com	TRUE	/	FALSE	${expireTime}	SESSDATA	${newSessdata}`,
            `.bilibili.com	TRUE	/	FALSE	${expireTime}	bili_jct	${newBiliJct}`,
            
            // 补充其他必要的cookie
            `.bilibili.com	TRUE	/	FALSE	${expireTime}	buvid3	XY1234567890`,
            `.bilibili.com	TRUE	/	FALSE	${expireTime}	b_nut	${Math.floor(Date.now() / 1000)}`,
            `.bilibili.com	TRUE	/	FALSE	${expireTime}	DedeUserID	123456789`,
            `.bilibili.com	TRUE	/	FALSE	${expireTime}	DedeUserID__ckMd5	abcdef1234567890`,
            `.bilibili.com	TRUE	/	FALSE	${expireTime}	sid	abcd1234`,
            
            // live.bilibili.com 域名
            `.live.bilibili.com	TRUE	/	FALSE	${expireTime}	SESSDATA	${newSessdata}`,
            `.live.bilibili.com	TRUE	/	FALSE	${expireTime}	bili_jct	${newBiliJct}`,
            
            // passport.bilibili.com 域名
            `.passport.bilibili.com	TRUE	/	FALSE	${expireTime}	SESSDATA	${newSessdata}`,
            `.passport.bilibili.com	TRUE	/	FALSE	${expireTime}	bili_jct	${newBiliJct}`,
            
            // api.bilibili.com 域名
            `.api.bilibili.com	TRUE	/	FALSE	${expireTime}	SESSDATA	${newSessdata}`,
            `.api.bilibili.com	TRUE	/	FALSE	${expireTime}	bili_jct	${newBiliJct}`
        ];

        // 写入新的cookie文件
        fs.writeFileSync(cookiePath, cookieLines.join('\n'));
        
        console.log('✅ Cookie更新成功！');
        console.log(`📁 文件位置: ${cookiePath}`);
        console.log(`🔑 SESSDATA: ${newSessdata.substring(0, 20)}...`);
        console.log(`🔑 bili_jct: ${newBiliJct}`);
        console.log(`⏰ 过期时间: ${new Date(expireTime * 1000).toLocaleString('zh-CN')}`);
        
        // 验证文件是否正确写入
        if (fs.existsSync(cookiePath)) {
            const fileSize = fs.statSync(cookiePath).size;
            console.log(`📊 文件大小: ${fileSize} 字节`);
            
            // 读取并验证内容
            const content = fs.readFileSync(cookiePath, 'utf-8');
            if (content.includes(newSessdata) && content.includes(newBiliJct)) {
                console.log('✅ 验证成功，关键cookie已正确写入');
            } else {
                console.log('⚠️ 警告：文件写入可能有问题');
            }
        }
        
    } catch (error) {
        console.error('❌ 更新cookie失败:', error);
        return false;
    }
    
    return true;
}

// 如果直接运行此脚本
if (require.main === module) {
    const success = updateCookies();
    if (success) {
        console.log('\n🎉 Cookie更新完成！您现在可以使用B站送礼功能了。');
    } else {
        console.log('\n💥 Cookie更新失败，请检查错误信息。');
        process.exit(1);
    }
}

module.exports = { updateCookies, newSessdata, newBiliJct };